export const countries = [
  { value: "25", label: "Angola, אוגנדה" },
  { value: "26", label: "Uzbekistan אוזבקיסטן" },
  { value: "221", label: "אוסטריה Austria " },
  { value: "27", label: "אוסטרליהAustralia" },
  { value: "28", label: "אוקראינה Ukraine" },
];

// const data = [{value :"29" ,אורוגואיlabel :""},
// {value :"30" ,אזרבייג&#39;label :""},
// {value :"31" ,איחוד הנסיכויות האמיריותlabel :""},
// {value :"32" ,איטליהlabel :""},
// {value :"33" ,איי בהאמהlabel :""},
// {value :"34" ,איי הבתולה האמריקאיםlabel :""},
// {value :"35" ,איי הבתולה הבריטייםlabel :""},
// {value :"37" ,איי טורק וקאיקוסlabel :""},
// {value :"38" ,איי כף וורדהlabel :""},
// {value :"40" ,איי סיישלlabel :""},
// {value :"41" ,איי פארוlabel :""},
// {value :"226" ,איי פוקלנדlabel :""},
// {value :"44" ,איי קיימןlabel :""},
// {value :"46" ,אינדונזיהlabel :""},
// {value :"47" ,איסלנדlabel :""},
// {value :"48" ,אירלנדlabel :""},
// {value :"50" ,אל סלוודורlabel :""},
// {value :"51" ,אלבניהlabel :""},
// {value :"52" ,אלג&#39;יריהlabel :""},
// {value :"53" ,אנגווילהlabel :""},
// {value :"54" ,אנגולהlabel :""},
// {value :"55" ,אנגליה / בריטניהlabel :""},
// {value :"228" ,אנדורהlabel :""},
// {value :"56" ,אנטיגואה וברבודהlabel :""},
// {value :"57" ,אסטוניהlabel :""},
// {value :"58" ,אפגניסטאןlabel :""},
// {value :"59" ,אקוודורlabel :""},
// {value :"60" ,ארגנטינהlabel :""},
// {value :"61" ,ארה&quot;ב / ארצות הבריתlabel :""},
// {value :"63" ,ארובהlabel :""},
// {value :"64" ,ארמניהlabel :""},
// {value :"66" ,בולגריהlabel :""},
// {value :"68" ,בוסניה-הרצגובינהlabel :""},
// {value :"71" ,בחרייןlabel :""},
// {value :"72" ,בלארוסlabel :""},
// {value :"73" ,בלגיהlabel :""},
// {value :"232" ,בליזlabel :""},
// {value :"74" ,בנגלדשlabel :""},
// {value :"76" ,ברבדוסlabel :""},
// {value :"77" ,ברונייlabel :""},
// {value :"78" ,ברזילlabel :""},
// {value :"248" ,ברמודהlabel :""},
// {value :"81" ,גאנהlabel :""},
// {value :"82" ,גואדלופlabel :""},
// {value :"83" ,גואטמלהlabel :""},
// {value :"85" ,גיאורגיהlabel :""},
// {value :"87" ,גיברלטרlabel :""},
// {value :"91" ,גינאה הצרפתיתlabel :""},
// {value :"80" ,ג&#39;מאיקהlabel :""},
// {value :"92" ,גמביהlabel :""},
// {value :"93" ,גרינלנדlabel :""},
// {value :"94" ,גרמניהlabel :""},
// {value :"95" ,גרנדהlabel :""},
// {value :"96" ,דומיניקהlabel :""},
// {value :"97" ,דנמרקlabel :""},
// {value :"98" ,דרום אפריקהlabel :""},
// {value :"99" ,האיטיlabel :""},
// {value :"100" ,האנטילים ההולנדייםlabel :""},
// {value :"101" ,הודוlabel :""},
// {value :"102" ,הולנדlabel :""},
// {value :"103" ,הונג קונגlabel :""},
// {value :"104" ,הונגריהlabel :""},
// {value :"105" ,הונדורסlabel :""},
// {value :"106" ,הרפובליקה הדומיניקניתlabel :""},
// {value :"107" ,הרפובליקה הדמוקרטית של קונגוlabel :""},
// {value :"110" ,ויאטנאםlabel :""},
// {value :"116" ,טאיוואןlabel :""},
// {value :"115" ,טג&#39;יקיסטןlabel :""},
// {value :"118" ,טוניסיהlabel :""},
// {value :"119" ,טורקיהlabel :""},
// {value :"121" ,טנזניהlabel :""},
// {value :"122" ,טרינידד וטובגוlabel :""},
// {value :"123" ,יווןlabel :""},
// {value :"124" ,יפןlabel :""},
// {value :"125" ,ירדןlabel :""},
// {value :"126" ,ישראלlabel :""},
// {value :"127" ,כוויתlabel :""},
// {value :"129" ,לבנוןlabel :""},
// {value :"131" ,לוקסמבורגlabel :""},
// {value :"132" ,לטביהlabel :""},
// {value :"133" ,ליבריהlabel :""},
// {value :"134" ,ליטאlabel :""},
// {value :"135" ,ליכטנשטייןlabel :""},
// {value :"137" ,מאוריציוסlabel :""},
// {value :"138" ,מאלדיבייםlabel :""},
// {value :"141" ,מוזמביקlabel :""},
// {value :"142" ,מולדובהlabel :""},
// {value :"143" ,מונגוליהlabel :""},
// {value :"144" ,מונטנגרוlabel :""},
// {value :"227" ,מונטסראטlabel :""},
// {value :"145" ,מונקוlabel :""},
// {value :"237" ,מיאנמר / בורמהlabel :""},
// {value :"147" ,מלזיהlabel :""},
// {value :"148" ,מלטהlabel :""},
// {value :"149" ,מצרייםlabel :""},
// {value :"150" ,מקאוlabel :""},
// {value :"151" ,מקדוניהlabel :""},
// {value :"152" ,מקסיקוlabel :""},
// {value :"153" ,מקסיקו (סים ישן*)label :""},
// {value :"154" ,מרוקוlabel :""},
// {value :"155" ,מרטיניקlabel :""},
// {value :"225" ,נורווגיהlabel :""},
// {value :"159" ,ניגריהlabel :""},
// {value :"160" ,ניו-זילנדlabel :""},
// {value :"161" ,ניקרגואהlabel :""},
// {value :"162" ,נמיביהlabel :""},
// {value :"163" ,נפאלlabel :""},
// {value :"166" ,סוריהlabel :""},
// {value :"247" ,סורינאםlabel :""},
// {value :"168" ,סיירה לאונהlabel :""},
// {value :"169" ,סיןlabel :""},
// {value :"229" ,סין (סים ישן)label :""},
// {value :"170" ,סינגפורlabel :""},
// {value :"171" ,סלובניהlabel :""},
// {value :"172" ,סלובקיהlabel :""},
// {value :"164" ,סן מרינוlabel :""},
// {value :"175" ,סנט וינסנט / גרנדיניםlabel :""},
// {value :"176" ,סנט לוצ&#39;יהlabel :""},
// {value :"177" ,סנט קיטסlabel :""},
// {value :"178" ,ספרדlabel :""},
// {value :"179" ,סקוטלנדlabel :""},
// {value :"180" ,סרביהlabel :""},
// {value :"181" ,סרי לנקהlabel :""},
// {value :"182" ,עומןlabel :""},
// {value :"183" ,עירקlabel :""},
// {value :"184" ,ערב הסעודית / סעודיהlabel :""},
// {value :"188" ,פוליןlabel :""},
// {value :"186" ,פורטו ריקוlabel :""},
// {value :"187" ,פורטו ריקו (סים ישן*)label :""},
// {value :"190" ,פורטוגלlabel :""},
// {value :"191" ,פיליפיניםlabel :""},
// {value :"192" ,פינלנדlabel :""},
// {value :"193" ,פנמהlabel :""},
// {value :"262" ,פקיסטןlabel :""},
// {value :"195" ,פרגוואיlabel :""},
// {value :"196" ,פרוlabel :""},
// {value :"199" ,צ&#39;ילהlabel :""},
// {value :"198" ,צ&#39;כיהlabel :""},
// {value :"200" ,צרפתlabel :""},
// {value :"203" ,קולומביהlabel :""},
// {value :"204" ,קוסובוlabel :""},
// {value :"205" ,קוסטה ריקהlabel :""},
// {value :"206" ,קוריאה הדרומיתlabel :""},
// {value :"201" ,קזחסטןlabel :""},
// {value :"207" ,קטארlabel :""},
// {value :"208" ,קירג&#39;יסטןlabel :""},
// {value :"209" ,קמבודיהlabel :""},
// {value :"210" ,קנדהlabel :""},
// {value :"212" ,קניהlabel :""},
// {value :"213" ,קפריסיןlabel :""},
// {value :"256" ,קפריסין הטורקיתlabel :""},
// {value :"214" ,קרואטיהlabel :""},
// {value :"109" ,קריית הוותיקןlabel :""},
// {value :"215" ,רומניהlabel :""},
// {value :"216" ,רוסיהlabel :""},
// {value :"217" ,שבדיהlabel :""},
// {value :"218" ,שוויץlabel :""},
// {value :"234" ,שייט בלב ים קבוצה 1label :""},
// {value :"239" ,שייט בלב ים קבוצה 2label :""},
// {value :"219" ,תאילנד</value :
// }];

export const faqData = [
  {
    title: "Item 1",
    content:
      "Lorem ipsum dolor amet gastropub church-key gentrify actually tacos. Vegan taxidermy freegan before they sold out kickstarter copper mug iceland selvage blog prism. 8-bit vice drinking vinegar stumptown locavore. Microdosing unicorn typewriter sartorial cornhole. Man bun venmo cronut wolf shaman offal truffaut. Chillwave vinyl pug distillery adaptogen man bun tofu retro hammock kogi tbh jean shorts organic. Craft beer vinyl etsy, portland microdosing chicharrones lumbersexual crucifix cronut gentrify four loko tousled fingerstache.",
  },
  {
    title: "Item 2",
    content:
      "Slow-carb knausgaard health goth kombucha tousled four loko. Messenger bag cronut +1, four loko williamsburg you probably haven't heard of them bicycle rights taiyaki ramps squid vaporware. Green juice typewriter master cleanse distillery viral wayfarers asymmetrical quinoa health goth semiotics succulents kinfolk pork belly shaman. Cronut salvia farm-to-table kickstarter shaman cloud bread echo park.",
  },
  {
    title: "Item 3",
    content:
      "Health goth humblebrag live-edge meggings pork belly actually ugh kombucha banh mi plaid etsy waistcoat. Hammock celiac crucifix tousled, dreamcatcher tbh truffaut direct trade cliche synth hot chicken palo santo pork belly man bun retro. Art party +1 live-edge occupy iceland selfies beard fanny pack godard 90's messenger bag. Bushwick irony umami woke. Kale chips raw denim austin, food truck flexitarian 90's deep v. Locavore green juice cold-pressed hexagon copper mug vegan sriracha man bun la croix photo booth forage. Succulents migas irony hella mumblecore keytar waistcoat aesthetic cornhole shabby chic tumblr semiotics readymade.",
  },
  {
    title: "Item 4",
    content:
      "Tbh next level subway tile ennui cloud bread. Master cleanse vaporware food truck, authentic distillery meggings ugh activated charcoal iceland gastropub fam. Raw denim direct trade pinterest keytar fam echo park wolf four dollar toast glossier kitsch taiyaki 8-bit austin. Brunch pinterest raw denim banh mi, bushwick organic artisan synth poutine man bun scenester. Occupy chartreuse food truck banh mi affogato shaman.",
  },
  {
    title: "Item 5",
    content:
      "Aesthetic tofu dreamcatcher lumbersexual jianbing poke PBR&B kogi heirloom. Sartorial artisan synth tacos vegan bushwick, lomo thundercats VHS disrupt bespoke scenester. Copper mug taiyaki occupy, coloring book drinking vinegar taxidermy direct trade intelligentsia quinoa raw denim succulents. Dreamcatcher copper mug fanny pack yuccie art party hoodie, ugh portland.",
  },
  {
    title: "Item 6",
    content: "Oh. You need a little dummy text for your mockup? How quaint.",
  },
];
